[package]
name = "fyre_fractal_function"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.*", features = ["derive"] }
criterion = "0.7.0"
gnuplot = "0.0.46"
rayon = "1.10.0"


[profile.release]
lto = "fat"
codegen-units = 1

[[bench]]
name = "bench"
harness = false
